import { CompletionMotion } from '../../CompletionMotion';
/* eslint-disable react-refresh/only-export-components -- Episode registry consumes a definition with its colocated physical scene. */
import { useState, type ReactNode } from 'react';
import type { EpisodeDefinition, EpisodeProps, EpisodeState } from '../types';
import { DetailModal } from '../components';
import { CRATES, PLATE_BASE_ANGLES, boundedArray, cargoReady, cargoTorque, plateJoined, putCrate, uniqueSlots } from './cargoLogic';
import './navigation.css';
import './cargoExploration.css';
import HarborEmblem from './HarborEmblem';
const initial=():EpisodeState=>({values:{exploration:1,cover:false,hook:false,plateRecovered:false,view:'quay',selected:0,scale:0,cubes:1,plate:[0,0,0],slots:[-1,-1,-1,-1],gate:false},solved:[],inventory:[],inspected:[]});
function normalize(s:EpisodeState):EpisodeState {
 const v=s.values, legacy=v.exploration!==1, slots=uniqueSlots(v.slots), plate=boundedArray(v.plate,3,0,3,[0,0,0]);
 const integer=(x:unknown,min:number,max:number,d:number)=>typeof x==='number'&&Number.isInteger(x)&&x>=min&&x<=max?x:d;
 const cover=v.cover===true, plateRecovered=legacy||v.plateRecovered===true;
 return {values:{exploration:1,cover,hook:v.hook===true,plateRecovered,view:['quay','deck','sluice'].includes(String(v.view))?v.view:'quay',selected:integer(v.selected,0,3,0),scale:integer(v.scale,0,3,0),cubes:integer(v.cubes,1,4,1),plate,slots:cover?slots:[-1,-1,-1,-1],gate:v.gate===true&&cover&&cargoReady(slots)},solved:plateJoined(plate)?['bow-plate']:[],inventory:[...(cover?CRATES.filter((_,i)=>!slots.includes(i)).map(c=>c.name):[]),...(v.hook?['长柄船钩']:[]),...(plateRecovered?['旧船首拼板']:[])],inspected:s.inspected.filter(id=>['scale','plate','boat'].includes(id))};
}
function CargoTarget({label,children,onActivate,disabled=false,selected=false}:{label:string;children:ReactNode;onActivate:()=>void;disabled?:boolean;selected?:boolean}) {
 return <g role="button" tabIndex={disabled?-1:0} aria-label={label} aria-disabled={disabled} aria-pressed={selected} className="cargo-art-target" onClick={()=>{if(!disabled)onActivate();}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(!disabled)onActivate();}}}>{children}</g>;
}
function Crate({id,x=0,y=0,size=50}:{id:number;x?:number;y?:number;size?:number}){return <g transform={`translate(${x} ${y})`}><rect width={size} height={size} rx="4" fill="#ba8955" stroke="#f4d69a" strokeWidth="2"/><path d={`M0 8H${size}M0 ${size-8}H${size}M8 0V${size}M${size-8} 0V${size}`} stroke="#76552f"/><HarborEmblem kind={['shell','leaf','star','fish'][id]} x={size*.2} y={size*.2} size={size*.6} color="#253a38"/></g>;}
function Plate({rotations}:{rotations:number[]}){return <svg viewBox="0 0 600 210" aria-label="三块方形船首拼板，板上的船身与边缘铆钉随转动一起旋转"><rect x="0" y="4" width="600" height="200" rx="9" fill="#79634b"/>{rotations.map((r,i)=><g key={i} transform={`translate(${i*200+100} 104)`}><rect x="-94" y="-94" width="188" height="188" fill="#d4c598" stroke="#f9e8b6"/><g transform={`rotate(${PLATE_BASE_ANGLES[i]+r*90})`}><path d={i===0?'M85 -37H-45Q-87 0-45 37H85':i===1?'M-94 -37H94V37H-94':'M-94 -37H15L88 0 15 37H-94'} fill="#587c77" stroke="#294b4b" strokeWidth="4"/><path d="M-86 0H86" stroke="#dfb469" strokeWidth="3"/>{i===2&&<><path d="M-33 -44H27V44H-33Z" fill="#e5cca0" stroke="#855d3c"/><HarborEmblem kind="star" x={-25} y={-22} size={44} color="#394744"/></>}<circle cx="-76" cy="-73" r="5" fill="#61462f"/><circle cx="-62" cy="-73" r="3" fill="#61462f"/><path d="M64 73H84V53" stroke="#61462f" fill="none" strokeWidth="3"/></g></g>)}</svg>;}
function Cargo({state,update,complete,announce,mode}:EpisodeProps){
 const [detail,setDetail]=useState<'scale'|'plate'|null>(null),[held,setHeld]=useState<number|null>(null),[tool,setTool]=useState(false),[feedback,setFeedback]=useState('');
 const v=state.values,slots=v.slots as number[],plate=v.plate as number[],view=String(v.view),launched=v.gate===true,torque=cargoTorque(slots);
 const patch=(values:EpisodeState['values'])=>update({values});
 const say=(message:string)=>{setFeedback(message);announce(message);};
 const cancel=()=>{setHeld(null);setTool(false);say('已放下手中的选择，物件留在原处。');};
 const travel=(next:string)=>{setHeld(null);setTool(false);setDetail(null);setFeedback('');patch({view:next});};
 const open=(id:'scale'|'plate')=>{setDetail(id);update({inspected:[...new Set([...state.inspected,id])]});};
 const pick=(id:number)=>{if(!v.cover||launched)return;setHeld(id);say(`拿起${CRATES[id].name}。选择船格放下，或选择码头搬回。`);};
 const place=(slot:number)=>{if(!v.cover||launched)return;if(held===null){if(slots[slot]>=0)pick(slots[slot]);else say('这里是空船格。先拿起一个木箱。');return;}const swapped=slots[slot]>=0&&slots[slot]!==held;patch({slots:putCrate(slots,held,slot),gate:false});setHeld(null);say(swapped?'木箱交换了位置。船身随重量重新倾斜。':'木箱已放下。船身随重量重新倾斜。');};
 const remove=()=>{if(held===null||launched)return;patch({slots:slots.map(id=>id===held?-1:id),gate:false});setHeld(null);say('木箱搬回码头。');};
 const test=()=>{if(launched){say('小船已经通过水闸，桥板仍然放着。');return;}if(cargoReady(slots)){patch({gate:true});setHeld(null);complete();say('船身平稳穿过水闸，船首的小桥放了下来。');}else say('水流推来，小船没能穿过闸口。船夫把船拉回，货物仍在原位。');};
 return <div className="cargo-exploration" onKeyDown={e=>{if(e.key==='Escape')cancel();}}>
 <nav aria-label="码头视点" className="navigation-controls">{[['quay','货物码头'],['deck','小船甲板'],['sluice','下游水闸']].map(([id,name])=><button key={id} aria-label={`前往${name}`} aria-pressed={view===id} onClick={()=>travel(id)}>{name}</button>)}</nav>
 <p className="cargo-operation">点选画面中的物件，也可用 Tab 和回车操作。{view==='deck'?'拿起木箱后选择船格；已有箱子的船格会交换位置。选择码头可搬回，Esc 可取消。':view==='sluice'?'可以查看闸边的东西，选中工具后再点它要接触的位置。':mode==='easy'?'看看棚下和岸边；物件拿走后，原来的位置仍可查看。':'物件拿走后，原来的位置仍可查看。'}</p>
 <section className="campaign-scene navigation-cargo"><svg viewBox="0 0 1000 440" aria-label={view==='quay'?'货物码头，棚布、称量台和靠岸的船钩':view==='deck'?'可直接搬运木箱的小船甲板':'下游水闸与漂浮船板'}>
 <rect width="1000" height="440" fill="#acc2ae"/><circle cx="845" cy="65" r="34" fill="#f3dca1"/><path d="M0 150 95 108 210 157 335 101 475 151 650 120 800 158 1000 113V280H0Z" fill="#738f83"/><rect y="270" width="1000" height="170" fill="#416e74"/><path d="M0 330Q130 310 260 330T520 330T780 330T1040 330M0 388Q130 370 260 388T520 388T780 388T1040 388" stroke="#9fbcb0" fill="none"/>
 {view==='quay'?<><path d="M0 272H790V302H0M90 300V410M690 300V410" stroke="#775537" strokeWidth="22" fill="none"/>
 <CargoTarget label={v.cover?'检查空帆布':'掀开货物帆布'} onActivate={()=>{patch({cover:true});say(v.cover?'帆布已经叠在棚边。':'帆布掀开，木箱露了出来。');}}><path d={v.cover?'M60 234H158L145 264H53Z':'M42 257 81 119H382L426 257Z'} fill="#587b79" stroke="#ddc58e" strokeWidth="5"/></CargoTarget>
 {v.cover&&CRATES.map((_,i)=>!slots.includes(i)&&<CargoTarget key={i} label={`拿起${CRATES[i].name}`} disabled={launched} onActivate={()=>{patch({view:'deck'});pick(i);}}><Crate id={i} x={170+i*57} y={211} size={49}/></CargoTarget>)}
 <CargoTarget label="检查两盘天平" onActivate={()=>open('scale')}><rect x="505" y="121" width="223" height="156" rx="14" fill="#345853"/><path d="M618 141V254M579 254H657M528 164H708M542 164V218M694 164V218" stroke="#e3c48a" strokeWidth="6" fill="none"/><path d="M513 217Q542 253 571 217M665 217Q694 253 723 217" fill="#aa9468"/></CargoTarget>
 <CargoTarget label={v.hook?'检查船钩原处':'拿起长柄船钩'} onActivate={()=>{patch({hook:true});say(v.hook?'岸边只剩船钩压过的浅痕，船钩在工具袋里。':'拿起长柄船钩。');}}><rect x="815" y="128" width="92" height="168" rx="14" fill="#5e7b6e"/>{!v.hook?<path d="M844 279V159Q844 122 876 149V177" fill="none" stroke="#edcf98" strokeWidth="12"/>:<path d="M844 279V162" stroke="#b3aa89" strokeWidth="3"/>}</CargoTarget></>:
 view==='deck'?<><CargoTarget label="码头放回区" onActivate={remove} disabled={launched}><rect x="18" y="64" width="964" height="92" rx="12" fill="#856745" stroke={held!==null?'#ffe29b':'#c5a77b'} strokeWidth="4"/></CargoTarget>{v.cover&&CRATES.map((c,i)=>!slots.includes(i)&&<CargoTarget key={i} label={`拿起${c.name}`} selected={held===i} disabled={launched} onActivate={()=>pick(i)}><Crate id={i} x={115+i*200} y={78} size={62}/></CargoTarget>)}
 <g transform={`rotate(${Math.max(-12,Math.min(12,torque*1.2))} 500 301)`}><path d="M75 300H930L844 389H158Z" fill="#9b7049" stroke="#e5c996" strokeWidth="5"/><path d="M818 300V193H922V299" fill="none" stroke="#e1c695" strokeWidth="9"/>{slots.map((id,i)=><CargoTarget key={i} label={`货舱第${i+1}格`} disabled={!v.cover||launched} selected={held!==null&&held===id} onActivate={()=>place(i)}><rect x={155+i*197} y="213" width="85" height="85" rx="4" fill="#344f4c" stroke={held!==null&&held===id?'#ffdf7f':'#d6bd8d'} strokeWidth="4" strokeDasharray={id<0?'6 5':undefined}/>{id>=0&&<Crate id={id} x={159+i*197} y={217} size={77}/>}<text x={198+i*197} y="322" fill="#ffe5b2" fontSize="18" textAnchor="middle">{i+1}</text></CargoTarget>)}<path d="M500 301V366" stroke="#e3cb99" strokeWidth="4"/></g><path d="M500 392V410" stroke="#e3cb99" strokeWidth="4"/>{mode!=='challenge'&&!v.cover&&<text x="500" y="110" textAnchor="middle" fill="#fff1cc" fontSize="20">码头的帆布还盖着货物</text>}</>:
 <><path d="M605 72H950V309H605Z" fill="#786c54"/><path d="M646 300V169Q780 42 910 169V300" fill="#263f3e"/><CompletionMotion milestone="gate" motion="lift"><path d={launched?'M655 138H899V170H655Z':'M655 176H899V300H655Z'} fill="#b49c70" stroke="#ddc694" strokeWidth="6"/></CompletionMotion><CargoTarget label="扳动水闸把手" onActivate={test}><rect x="465" y="168" width="94" height="118" rx="8" fill="#55716a"/><path d="M510 265V201L550 176" fill="none" stroke="#e5c897" strokeWidth="13"/><circle cx="551" cy="176" r="13" fill="#72553c"/></CargoTarget>
 <CargoTarget label={v.plateRecovered?'检查船板原处':'钩取漂浮船板'} onActivate={()=>{if(v.plateRecovered){say('水边已经没有船板了，捞起的拼板放在闸旁。');return;}if(!tool){say('船板卡在下游木桩外，伸手够不到。');return;}patch({plateRecovered:true});setTool(false);say('船钩勾住边缘，旧船板被拖到闸旁。');}}><path d="M82 338H370V366H82Z" fill="#416e74" stroke="#88aba3"/>{!v.plateRecovered&&<g transform="translate(144 302) rotate(-8)"><rect width="190" height="55" fill="#c3b084"/><path d="M12 27H179" stroke="#547878" strokeWidth="12"/></g>}<path d="M102 278V380M357 290V394" stroke="#785a3f" strokeWidth="14"/></CargoTarget>
 {v.plateRecovered&&<CargoTarget label="检查旧船首拼板" onActivate={()=>open('plate')}><rect x="44" y="93" width="355" height="145" rx="12" fill="#8d7453"/><svg x="53" y="104" width="337" height="119"><Plate rotations={plate}/></svg></CargoTarget>}
 <CompletionMotion milestone="gate" motion="sail">{launched&&<g><path d="M662 280H891L858 322H696Z" fill="#956c49" stroke="#ddc493" strokeWidth="4"/>{slots.map((id,i)=>id>=0&&<Crate key={i} id={id} x={691+i*41} y={249} size={32}/>)}<path d="M850 284H978" stroke="#f0d4a0" strokeWidth="12"/></g>}</CompletionMotion></>}
 </svg></section>
 {view==='sluice'&&v.hook&&<div className="navigation-controls"><button aria-label="使用长柄船钩" aria-pressed={tool} onClick={()=>{setTool(!tool);say(tool?'船钩收回工具袋。':'船钩拿在手中，选择要勾取的位置。');}}>长柄船钩</button></div>}
 {view==='deck'&&<><p aria-live="polite">船身{torque===0?'水平':torque>0?'向船首倾斜':'向船尾倾斜'}。{held===null?'手中没有木箱。':`手中：${CRATES[held].name}`}</p><details><summary>木箱操作按钮</summary><div className="navigation-controls">{CRATES.map((c,i)=><button key={i} disabled={!v.cover||launched} aria-pressed={held===i} onClick={()=>pick(i)}>拿起{c.name}</button>)}{slots.map((_,i)=><button key={i} disabled={!v.cover||launched} onClick={()=>place(i)}>放入货舱第{i+1}格</button>)}<button disabled={held===null||launched} onClick={remove}>搬回码头</button></div></details></>}
 {(held!==null||tool)&&<button aria-label="取消拿取" onClick={cancel}>取消拿取</button>}
 <p className="cargo-feedback" role="status">{feedback}</p>
 {detail&&<DetailModal title={detail==='scale'?'两盘天平':'旧船首拼板'} onClose={()=>setDetail(null)}>{detail==='scale'?<><p>把木箱放到左盘，右盘可以添加或取走黄铜小方块。</p><svg viewBox="0 0 640 330" aria-label={!v.cover?'左盘空着，货物尚未露出':`左盘${CRATES[v.scale as number].name}，右盘${v.cubes}块黄铜，${CRATES[v.scale as number].mass===(v.cubes as number)?'横梁水平':CRATES[v.scale as number].mass>(v.cubes as number)?'左盘下沉':'右盘下沉'}`}><path d="M320 78V292M245 299H395" stroke="#d9bc81" strokeWidth="11"/><g transform={`rotate(${((v.cubes as number)-(v.cover?CRATES[v.scale as number].mass:0))*5} 320 100)`}><path d="M120 100H520M140 100V230M500 100V230" stroke="#e1c892" strokeWidth="6"/><path d="M76 233Q140 290 204 233M436 233Q500 290 564 233" fill="#9d8858" stroke="#dcc18f" strokeWidth="4"/>{v.cover&&<Crate id={v.scale as number} x={114} y={173} size={52}/>}{Array.from({length:v.cubes as number},(_,i)=><rect key={i} x={455+(i%2)*44} y={205-Math.floor(i/2)*28} width="37" height="24" fill="#d6b86e" stroke="#ffdb91"/>)}</g><circle cx="320" cy="100" r="14" fill="#e6cc91"/></svg><div className="navigation-controls">{CRATES.map((c,i)=><button key={c.name} disabled={!v.cover} aria-pressed={v.scale===i} onClick={()=>patch({scale:i})}>称{c.name}</button>)}<button disabled={(v.cubes as number)<=1} onClick={()=>patch({cubes:(v.cubes as number)-1})}>取走一块黄铜</button><button disabled={(v.cubes as number)>=4} onClick={()=>patch({cubes:(v.cubes as number)+1})}>添加一块黄铜</button></div>{!v.cover&&<p>码头上的货物还盖着帆布。</p>}</>:<><Plate rotations={plate}/><div className="navigation-controls">{plate.map((r,i)=><button key={i} aria-label={`转动第${i+1}块船板`} onClick={()=>patch({plate:plate.map((x,j)=>j===i?(r+1)%4:x)})}>转动第{i+1}块 ↻</button>)}</div><p>木板可以自由旋转。船身、铆钉和边框都保留在图上，随时可以回来查看。</p></>}</DetailModal>}
 </div>;
}
export const cargoEpisode:EpisodeDefinition={id:'cargo',title:'小船的平衡货舱',place:'码头 · 称量台 · 船闸',description:'称量木箱，读懂旧船的模样，让满载的小船平稳出港。',motif:'cargo',initial,normalize,isComplete:s=>s.values.gate===true&&s.values.cover===true&&cargoReady(s.values.slots as number[]),hints:()=>['可以往返货物码头和下游水闸。称量台和旧船板提供不同的线索。','岸边的长柄船钩能够到漂浮船板。天平的黄铜块一样重，船上离中心越远的位置作用越大；拼好的旧船板保留了船首的样子。','掀开帆布，拿起长柄船钩，到下游水闸选中船钩，再点漂浮船板。贝壳、树叶、星星、小鱼分别重1、2、3、4块。拼板转动2、1、3次。船尾到船首放树叶、小鱼、贝壳、星星，再到下游扳水闸。'],Component:Cargo};
