import { useState } from 'react';
import type { ReactNode, PointerEvent } from 'react';
import {swapAt} from './clockworkState';
import './clockworkShared.css';
/** Drag the actual artwork. Two-tap selection and destination are the keyboard/touch alternative. */
export function ObjectRow({items,onChange,render,label,slotLabels,disabled=false}:{items:number[];onChange:(next:number[])=>void;render:(item:number,slot:number)=>ReactNode;label:string;slotLabels?:string[];disabled?:boolean}){
 const [selected,setSelected]=useState<number|null>(null);const [drag,setDrag]=useState<{index:number,x:number,y:number,startX:number,startY:number}|null>(null);
 const pick=(i:number)=>{if(disabled)return;if(selected===null)setSelected(i);else {onChange(swapAt(items,selected,i));setSelected(null);}};
 const end=(e:PointerEvent<SVGSVGElement>)=>{if(!drag)return;const box=e.currentTarget.getBoundingClientRect();const to=Math.max(0,Math.min(items.length-1,Math.floor((e.clientX-box.left)/box.width*items.length)));if(Math.abs(e.clientX-drag.startX)+Math.abs(e.clientY-drag.startY)>8){onChange(swapAt(items,drag.index,to));setSelected(null);}setDrag(null);};
 return <div className="mech-object-row"><svg role="img" aria-label={label} viewBox={`0 0 ${items.length*150} 150`} onPointerMove={e=>{if(drag){const b=e.currentTarget.getBoundingClientRect();setDrag({...drag,x:(e.clientX-drag.startX)*items.length*150/b.width,y:(e.clientY-drag.startY)*150/b.height});}}} onPointerUp={end} onPointerCancel={()=>setDrag(null)}>
 {items.map((item,i)=><g key={i} transform={`translate(${i*150},0)`}><rect x="5" y="5" width="140" height="140" rx="15" fill={selected===i?'#fff1bf':'#fff8e6'} stroke={selected===i?'#f7bd5b':'#907351'} strokeWidth="3"/><g className="mech-grabbable" transform={drag?.index===i?`translate(${drag.x},${drag.y})`:undefined} onPointerDown={e=>{if(disabled)return;e.currentTarget.ownerSVGElement?.setPointerCapture(e.pointerId);setDrag({index:i,x:0,y:0,startX:e.clientX,startY:e.clientY});}}>{render(item,i)}</g></g>)}
 </svg><div className="mech-slot-controls" style={{gridTemplateColumns:`repeat(${items.length},1fr)`}}>{items.map((item,i)=><button key={i} type="button" aria-pressed={selected===i} onClick={()=>pick(i)} disabled={disabled}>{selected===null||selected===i?`拿起${slotLabels?.[i]??`第${i+1}格`}`:`放到${slotLabels?.[i]??`第${i+1}格`}`}<span className="mech-sr">，物件 {item}</span></button>)}</div></div>;
}
export function Workbench({title,children,onBack}:{title:string;children:ReactNode;onBack:()=>void}){return <section className="mech-bench" aria-label={title}><header><h2>{title}</h2><button onClick={onBack}>← 环顾四周</button></header>{children}</section>;}
export function TickRing({cx=75,cy=75,r=52}:{cx?:number;cy?:number;r?:number}){return <g>{Array.from({length:12},(_,i)=>{const a=i*Math.PI/6;return <path key={i} d={`M${cx+Math.sin(a)*(r-6)} ${cy-Math.cos(a)*(r-6)}L${cx+Math.sin(a)*r} ${cy-Math.cos(a)*r}`} stroke="#5a432e" strokeWidth={i===0?4:2}/>;})}<path d={`M${cx-4} ${cy-r-10}h8l-4 5z`} fill="#8c392c"/></g>;}
export function Bird({kind,x=0,y=0,scale=1}:{kind:number;x?:number;y?:number;scale?:number}){return <g transform={`translate(${x} ${y}) scale(${scale})`} fill={['#785845','#304e69','#e5e3cf'][kind]} stroke="#332f32" strokeWidth="2">{kind===0?<><path d="M-22 25Q-30 1-19-26L-9-15Q0-23 9-15L19-26Q30 1 22 25Z"/><circle cx="-9" cy="-4" r="7" fill="#ffdc87"/><circle cx="9" cy="-4" r="7" fill="#ffdc87"/><circle cx="-9" cy="-4" r="2"/><circle cx="9" cy="-4" r="2"/><path d="M-4 5L0 12L4 5" fill="#b77230"/></>:<><path d={kind===1?'M-35-20Q-5-7 0 0Q10-14 35-20L15 7L1 12L-11 27L-8 9Z':'M-34-8Q-8-20 0-2Q12-17 35-8L15 9L1 12L-20 16L-8 4Z'}/><path d="M12 2l13 4-13 4" fill="#d99736"/><circle cx="10" cy="3" r="2" fill="#222"/></>}</g>;}
export function Habitat({kind,x=0,y=0,scale=1}:{kind:number;x?:number;y?:number;scale?:number}){return <g transform={`translate(${x} ${y}) scale(${scale})`} fill="none" stroke={['#527450','#3f8eab','#336e52'][kind]} strokeWidth="3">{kind===0?<><path d="M-14 20Q-24-7-10-28M0 20V-30M14 20Q26-10 14-25"/><path d="M-13-18v-13M0-24v-14M14-16v-15" strokeWidth="7"/></>:kind===1?<><path d="M-30-10q15-15 30 0t30 0M-30 4q15-15 30 0t30 0M-30 18q15-15 30 0t30 0"/></>:<><path d="M0-34L-26 0h12l-18 22h64L14 0h12Z" fill="#4c8356"/><path d="M0 22v15" stroke="#76533b"/></>}</g>;}
