import { useState, type ReactNode } from 'react';
import type { EpisodeProps } from '../types';
import './radioMusicExploration.css';
import { guidancePolicy } from '../../guidancePolicy';
type Props=Pick<EpisodeProps,'state'|'update'|'announce'|'mode'> & {children:ReactNode;open:(panel:string)=>void};
function Outside({music,opened,values}:{music:boolean;opened:boolean;values:EpisodeProps['state']['values']}) {return <svg viewBox="0 0 1000 470" role="img" aria-label={music?'窗边凹室：风铃帘与带盖长凳':'临海检修平台：防雨罩与备用摇柄'}><rect width="1000" height="470" fill={music?'#ad8467':'#234c59'}/><path d="M0 360H1000V470H0Z" fill={music?'#704d39':'#736551'}/><rect x="80" y="45" width="840" height="265" rx="70" fill={music?'#d9dfbd':'#99c6c7'} stroke="#d9b67c" strokeWidth="12"/><path d="M85 220Q260 130 410 220T915 220V305H85" fill="#587f80"/><path d="M500 48V309M80 178H920" stroke="#b08c5d" strokeWidth="12"/>{music?<><path d={opened?'M110 45h130l-65 275H110ZM760 45H890V320H825Z':'M110 45H460V320H110ZM540 45H890V320H540Z'} fill="#97615d" stroke="#edc994" strokeWidth="6"/><rect x="300" y="322" width="400" height="99" rx="9" fill="#9c6c44" stroke="#e0ba78" strokeWidth="5"/>{values.seatOpen?<><path d="M300 322l48-72H720l-20 72" fill="#c1915e" stroke="#e0ba78" strokeWidth="5"/><rect x="320" y="334" width="360" height="35" fill="#493d30"/>{!values.paperFound&&<rect x="432" y="336" width="136" height="26" rx="12" fill="#f6ddab"/>}</>:<path d="M320 362H680" stroke="#493d30" strokeWidth="9"/>}{opened&&<><path d="M270 85H680" stroke="#79583e" strokeWidth="10"/>{(values.bars as number[]).map((bird,i)=><g key={i}><path d={`M${330+i*130} 85v30`} stroke="#79583e" strokeWidth="3"/><rect x={315+i*130} y="115" width="30" height={[9,6,4][bird]*16} rx="12" fill="#dbb46d" stroke="#79583e" strokeWidth="3"/></g>)}{!values.handleFound&&<path d="M744 157v64h32v-25" fill="none" stroke="#b4844d" strokeWidth="10"/>}</>}</>:<><path d="M100 328H900M150 330V460M850 330V460" stroke="#c9b787" strokeWidth="14"/><rect x="260" y="200" width="250" height="145" rx="12" fill="#35595a" stroke="#e1bc79" strokeWidth="5"/><path d={opened?'M260 200l65-90 205 36-20 54Z':'M260 200H510V280H260Z'} fill="#698276" stroke="#e1bc79" strokeWidth="5"/>{!values.crankFound&&<path d="M730 210v75h58v-30" fill="none" stroke="#dcba7c" strokeWidth="14"/>}{opened&&!values.fuseFound&&<g><rect x="350" y="285" width="70" height="16" rx="8" fill="#c7e5d4" stroke="#f1d994" strokeWidth="5"/></g>}{values.signalsHeard&&<g aria-label="接收后的应答灯"><circle cx="580" cy="200" r="20" fill="#fff0a4" className="signal-pulse"/><path d="M564 240h32" stroke="#ffe8ad" strokeWidth="5"/></g>}</>}</svg>;}
export function RadioExploration({state,update,announce,children,open,mode}:Props) {
 const [view,setView]=useState<'room'|'landing'>('room'),[held,setHeld]=useState<string|null>(null);const v=state.values;
 const change=(values:typeof state.values,message:string)=>{update({values});announce(message);};
 const use=(item:string,key:string,message:string)=>{if(held!==item){announce('这里有空的安装位置。先从工具袋拿起合适的物件，再触碰这里。');return;}change({[key]:true},message);setHeld(null);};
 return <><div className="radio-exploration-stage">{view==='room'?children:<div className="signal-art"><Outside music={false} opened={v.coverOpen===true} values={v}/></div>}<div className={`radio-exploration-targets${guidancePolicy(mode).markers ? '' : ' unmarked'}`}>{view==='landing'?<><button style={{left:'27%',top:'46%'}} onClick={()=>v.coverOpen?(v.fuseFound?announce('防雨罩内留下一个空的保险管夹。'):change({fuseFound:true},'从夹子里取下保险管，收进工具袋。')):change({coverOpen:true},'防雨罩向上翻开，露出一根玻璃保险管。')}>{!v.coverOpen?'翻开防雨罩':v.fuseFound?'查看空保险管夹':'取下玻璃保险管'}</button><button style={{left:'69%',top:'53%'}} onClick={()=>v.crankFound?announce('摇柄挂钩空着，海风吹过平台。'):change({crankFound:true},'从挂钩取下黄铜摇柄。')}>{v.crankFound?'查看空摇柄挂钩':'取下黄铜摇柄'}</button></>:<><button style={{left:'10%',top:'50%'}} onClick={()=>v.fuseInstalled?open('scope'):use('保险管','fuseInstalled','保险管坐进夹座，玻璃屏亮起。')}>{v.fuseInstalled?'掀开示波器罩':'检查接收机空保险座'}</button><button style={{left:'40%',top:'58%'}} onClick={()=>v.wiringOpen?open('wires'):change({wiringOpen:true},'接线台的铰链盖向后翻开，露出有棱角的接头。')}>{v.wiringOpen?'拉开接线台':'翻开接线台铰链盖'}</button><button style={{left:'70%',top:'70%'}} onClick={()=>v.crankInstalled?open('transmitter'):use('黄铜摇柄','crankInstalled','摇柄插进发报机的方轴，可以转动了。')}>{v.crankInstalled?'走到发报机':'检查发报机空摇柄轴'}</button></>}</div></div><nav className="signal-nav" aria-label="电台视角"><button onClick={()=>{setView(view==='room'?'landing':'room');open('room');}}>{view==='room'?'走到临海检修平台':'回到接收机房'}</button><button onClick={()=>open('room')}>收起近景</button></nav><div className="signal-toolbar" aria-label="电台工具袋">{v.fuseFound&&!v.fuseInstalled&&<button aria-pressed={held==='保险管'} onClick={()=>setHeld('保险管')}>拿起保险管</button>}{v.crankFound&&!v.crankInstalled&&<button aria-pressed={held==='黄铜摇柄'} onClick={()=>setHeld('黄铜摇柄')}>拿起黄铜摇柄</button>}{held&&<button onClick={()=>setHeld(null)}>收回手中物件</button>}</div><p className="signal-memory" aria-live="polite">{held?`手中拿着${held}，触碰要安装的位置。`:view==='landing'?'海风吹过检修平台，防雨罩和挂钩就在栏杆内侧。':v.fuseInstalled?'接收机玻璃亮着，保险管已装入夹座。':'接收机玻璃暗着，保险座内有两个空夹子。'}{v.crankInstalled&&' 发报机的摇柄已经装好。'}{v.wiringOpen&&' 接线台盖敞开着。'}</p></>;
}
export function MusicExploration({state,update,announce,children,open,mode}:Props) {
 const [view,setView]=useState<'room'|'window'>('window'),[held,setHeld]=useState<string|null>(null);const v=state.values;
 const change=(values:typeof state.values,message:string)=>{update({values});announce(message);};
 const use=(item:string,key:string,message:string)=>{if(held!==item){announce('这里留着空的安装位置。先拿起物件，再触碰这里。');return;}change({[key]:true},message);setHeld(null);};
 return <><div className="radio-exploration-stage">{view==='room'?children:<div className="signal-art"><Outside music opened={v.curtainOpen===true} values={v}/></div>}<div className={`radio-exploration-targets${guidancePolicy(mode).markers ? '' : ' unmarked'}`}>{view==='window'?<><button style={{left:'18%',top:'43%'}} onClick={()=>v.curtainOpen?open('chimes'):change({curtainOpen:true},'帘子收向两边，铜管和背板轮廓露出来，帘后还挂着一只木摇柄。')}>掀开风铃帘</button><button style={{left:'39%',top:'70%'}} onClick={()=>v.seatOpen?(v.paperFound?announce('长凳内留下卷轴压出的圆形痕迹。'):change({paperFound:true},'取出带鸟形纸孔的纸卷。')):change({seatOpen:true},'长凳盖打开，里面躺着一卷有鸟形纸孔的纸。')}>{!v.seatOpen?'抬起长凳盖':v.paperFound?'查看空长凳':'取出鸟形纸卷'}</button>{v.curtainOpen&&<button style={{left:'68%',top:'45%'}} onClick={()=>v.handleFound?announce('帘后的摇柄钩已经空了。'):change({handleFound:true},'从帘后取下木摇柄。')}>{v.handleFound?'查看空摇柄钩':'取下木摇柄'}</button>}</>:<><button style={{left:'12%',top:'67%'}} onClick={()=>v.paperInstalled?open('roll'):use('鸟形纸卷','paperInstalled','纸卷装进铜套，鸟形孔从开口露出来。')}>{v.paperInstalled?'查看打孔纸卷':'检查空铜套'}</button><button style={{left:'44%',top:'66%'}} onClick={()=>v.handleInstalled?open('drum'):use('木摇柄','handleInstalled','木摇柄装进八音盒，针筒盖向上打开。')}>{v.handleInstalled?'打开八音盒':'检查八音盒空转轴'}</button></>}</div></div><nav className="signal-nav" aria-label="音乐阁视角"><button onClick={()=>{setView(view==='room'?'window':'room');open('room');}}>{view==='room'?'走到窗边凹室':'走到八音盒工作台'}</button><button onClick={()=>open('room')}>收起近景</button></nav><div className="signal-toolbar" aria-label="音乐阁工具袋">{v.paperFound&&!v.paperInstalled&&<button aria-pressed={held==='鸟形纸卷'} onClick={()=>setHeld('鸟形纸卷')}>拿起鸟形纸卷</button>}{v.handleFound&&!v.handleInstalled&&<button aria-pressed={held==='木摇柄'} onClick={()=>setHeld('木摇柄')}>拿起木摇柄</button>}{held&&<button onClick={()=>setHeld(null)}>收回手中物件</button>}</div><p className="signal-memory" aria-live="polite">{held?`手中拿着${held}，触碰要安装的位置。`:view==='window'?`${v.curtainOpen?'风铃帘已拉开，铜管身后的轮廓清晰可见。':'布帘遮住窗边的挂架。'} ${v.seatOpen?'长凳盖敞开着。':''}`:`${v.paperInstalled?'纸卷装在铜套中。':'工作台铜套里空着。'} ${v.handleInstalled?'木摇柄装在八音盒侧面。':'八音盒侧面留着一个空的方孔。'}`}</p></>;
}
