import type { Cell, ChapterDefinition, DropPuzzle, Requirement } from "./types";
export const CHAPTER_KEY = "play-buddy:escape:foglight:v1";
const tool = (id: string): Requirement => ({ kind: "tool", id });
const reveal = (id: string): Requirement => ({ kind: "reveal", id });
const base = {
  easyHelp: "可以先观察实物线索，摆好后再整体确认；拿不准时可以撤销。",
  hints: [] as string[],
  requires: [] as Requirement[],
  rewards: [] as string[],
};
function fixedColumns(heights: number[]): Cell[] {
  return heights.flatMap((height, x) =>
    Array.from({ length: height }, (_, offset): Cell => [x, 7 - offset]),
  );
}
const dropBoards: DropPuzzle["boards"] = [
  {
    id: "drop-a",
    label: "甲 · T 形",
    model: {
      width: 6,
      height: 8,
      fixed: fixedColumns([1, 3, 0, 2, 4, 1]),
      pieces: [
        {
          id: "t",
          label: "T 形",
          cells: [
            [0, 0],
            [1, 0],
            [2, 0],
            [1, 1],
          ],
        },
      ],
    },
    placement: { pieceId: "t", rotation: 0, column: 1 },
  },
  {
    id: "drop-b",
    label: "乙 · 方形",
    model: {
      width: 6,
      height: 8,
      fixed: fixedColumns([2, 0, 4, 1, 3, 2]),
      pieces: [
        {
          id: "o",
          label: "方形",
          cells: [
            [0, 0],
            [1, 0],
            [0, 1],
            [1, 1],
          ],
        },
      ],
    },
    placement: { pieceId: "o", rotation: 0, column: 3 },
  },
  {
    id: "drop-c",
    label: "丙 · 长条",
    model: {
      width: 6,
      height: 8,
      fixed: fixedColumns([3, 0, 2, 1, 4, 2]),
      pieces: [
        {
          id: "i",
          label: "长条",
          cells: [
            [0, 0],
            [0, 1],
            [0, 2],
            [0, 3],
          ],
        },
      ],
    },
    placement: { pieceId: "i", rotation: 0, column: 1 },
  },
];
export const CHAPTER: ChapterDefinition = {
  id: "foglight",
  revision: 1,
  title: "归航之光",
  finish: "foglight-console",
  scenes: [
    {
      id: "gallery",
      title: "珍奇标本舱",
      description: "海鸟标本、旧纹片与航海员收藏的贝壳，守着光学镜架的秘密。",
      requires: [],
    },
    {
      id: "optics",
      title: "光学观测室",
      description: "月光穿过观测窗，三色镜片与潮汐板静静等待再次运转。",
      requires: [],
    },
    {
      id: "workshop",
      title: "雾灯工坊",
      description:
        "港湾隐在薄雾中。落块实验台旁，熄灭的雾灯还保留着温暖的铜色。",
      requires: [],
    },
  ],
  items: [
    {
      id: "brush",
      name: "软刷",
      symbol: "▰",
      description: "木柄顶端是一束细软的刷毛。",
    },
    {
      id: "hook",
      name: "长柄钩",
      symbol: "J",
      description: "细长的金属杆，末端弯成一个小钩。",
    },
    {
      id: "cloth",
      name: "镜布",
      symbol: "▱",
      description: "一块柔软、细密、不掉绒的方布。",
    },
    {
      id: "arrow-tiles",
      name: "箭纹片",
      symbol: "↑",
      description: "两枚带朝向与刻点的箭纹片。",
    },
    {
      id: "sail-tiles",
      name: "帆纹片",
      symbol: "◩",
      description: "两枚带朝向与刻点的帆纹片。",
    },
    {
      id: "vane-tiles",
      name: "风标纹片",
      symbol: "⚑",
      description: "两枚长短臂不同、带刻点的风标纹片。",
    },
    {
      id: "oil-can",
      name: "小油壶",
      symbol: "♧",
      description: "铜壶里盛着润滑油，壶嘴细长。",
    },
    {
      id: "lens-frame",
      name: "放大镜架",
      symbol: "⌕",
      description: "标本柜里的光学镜架，边缘留着圆形卡槽。",
    },
    {
      id: "filter-disc",
      name: "三色镜盘",
      symbol: "◉",
      description: "日、月、叶三个标记对应三种观察镜片。",
    },
    {
      id: "route-plate",
      name: "航路铭牌",
      symbol: "▤",
      description: "长方形铜铭牌，背面有两枚凸出的卡榫。",
    },
    {
      id: "winding-crank",
      name: "潮汐曲柄",
      symbol: "┐",
      description: "一支折角金属柄，末端是方形转轴。",
    },
    {
      id: "beacon-prism",
      name: "雾灯棱镜",
      symbol: "◇",
      description: "菱形玻璃棱镜，边缘闪着柔和的彩光。",
    },
  ],
  reveals: [
    {
      id: "pattern-engraving",
      scene: "gallery",
      label: "检查保养铭刻",
      clue: "铭刻：↑ → ↓ ← ↑；• → •• → ••• → •。",
      requires: [],
    },
    {
      id: "gallery-curtain",
      scene: "gallery",
      label: "掀开布帘",
      requires: [],
    },
    { id: "shell-fan", scene: "gallery", label: "抬起贝壳扇", requires: [] },
    { id: "rolled-chart", scene: "optics", label: "展开卷图", requires: [] },
    { id: "rope-coil", scene: "workshop", label: "移开盘绳", requires: [] },
  ],
  pickups: [
    {
      item: "brush",
      scene: "gallery",
      label: "取出布帘后的软刷",
      requires: [reveal("gallery-curtain")],
    },
    {
      item: "arrow-tiles",
      scene: "gallery",
      label: "拾起贝壳扇下的箭纹片",
      requires: [reveal("shell-fan")],
    },
    {
      item: "hook",
      scene: "optics",
      label: "取走卷图下面的长柄钩",
      requires: [reveal("rolled-chart")],
    },
    {
      item: "cloth",
      scene: "optics",
      label: "拾起望远镜旁的镜布",
      requires: [],
    },
    {
      item: "vane-tiles",
      scene: "workshop",
      label: "取出零件盘里的风标纹片",
      requires: [],
    },
    {
      item: "oil-can",
      scene: "workshop",
      label: "取走盘绳后的小油壶",
      requires: [reveal("rope-coil")],
    },
    {
      item: "sail-tiles",
      scene: "workshop",
      label: "拿起钩出的帆纹片",
      requires: [tool("hook-grate")],
    },
  ],
  tools: [
    {
      id: "brush-plaque",
      target: { closeup: "animal-cabinet", label: "积灰铭牌", description: "铭牌蒙着一层灰，刻痕看不清。", x: 20, y: 64, width: 60, height: 24 },
      scene: "gallery",
      item: "brush",
      label: "刷净标本铭牌",
      requires: [],
    },
    {
      id: "hook-grate",
      target: { closeup: "search", label: "格栅", description: "细窄的格栅后，有一叠够不到的纹片。", x: 67, y: 28, width: 27, height: 32 },
      scene: "workshop",
      item: "hook",
      label: "从格栅后钩取纹片",
      requires: [],
    },
    {
      id: "mount-arrow",
      installsItem: true,
      target: { closeup: "pattern-tray", label: "箭纹凹槽", description: "一对箭形凹槽，边缘留有卡口。", x: 10, y: 20, width: 23, height: 60 },
      scene: "gallery",
      item: "arrow-tiles",
      label: "把箭纹片放到纹片台",
      requires: [],
    },
    {
      id: "mount-sail",
      installsItem: true,
      target: { closeup: "pattern-tray", label: "帆纹凹槽", description: "一对帆形凹槽，边缘留有卡口。", x: 38, y: 20, width: 23, height: 60 },
      scene: "gallery",
      item: "sail-tiles",
      label: "把帆纹片放到纹片台",
      requires: [],
    },
    {
      id: "mount-vane",
      installsItem: true,
      target: { closeup: "pattern-tray", label: "风标凹槽", description: "一对风标形凹槽，边缘留有卡口。", x: 66, y: 20, width: 23, height: 60 },
      scene: "gallery",
      item: "vane-tiles",
      label: "把风标纹片放到纹片台",
      requires: [],
    },
    {
      id: "clean-window",
      target: { closeup: "lens-chart", label: "观测窗", description: "玻璃上的盐雾遮住了窗内的纸页。", x: 7, y: 12, width: 43, height: 75 },
      scene: "optics",
      item: "cloth",
      label: "擦净光学观测窗",
      requires: [],
    },
    {
      id: "mount-frame",
      installsItem: true,
      target: { closeup: "lens-chart", label: "镜架接口", description: "窗旁有一个圆环形接口，表面沾着盐粒。", x: 55, y: 20, width: 18, height: 60 },
      scene: "optics",
      item: "lens-frame",
      label: "装上放大镜架",
      requires: [tool("clean-window")],
    },
    {
      id: "mount-filter",
      installsItem: true,
      target: { closeup: "lens-chart", label: "镜盘卡槽", description: "侧面的圆形卡槽通向镜架，里面还没有镜盘。", x: 78, y: 20, width: 17, height: 60 },
      scene: "optics",
      item: "filter-disc",
      label: "装入三色镜盘",
      requires: [tool("mount-frame")],
    },
    {
      id: "mount-route",
      installsItem: true,
      target: { closeup: "gravity-lock", label: "铭牌嵌槽", description: "实验台下方有一块长方形空槽。", x: 20, y: 64, width: 60, height: 24 },
      scene: "workshop",
      item: "route-plate",
      label: "将航路铭牌装上实验台",
      requires: [],
    },
    {
      id: "wind-tide",
      installsItem: true,
      target: { closeup: "tide-sudoku", label: "摇柄插孔", description: "棋盘旁的方轴孔通向停住的齿轮。", x: 75, y: 29, width: 19, height: 46 },
      scene: "optics",
      item: "winding-crank",
      label: "用曲柄启动潮汐板",
      requires: [],
    },
    {
      id: "oil-track",
      target: { closeup: "foglight-console", label: "底座轨道", description: "轨道上有干涩的锈迹，灯座卡住了。", x: 13, y: 70, width: 74, height: 19 },
      scene: "workshop",
      item: "oil-can",
      label: "润滑雾灯底座轨道",
      requires: [],
    },
    {
      id: "mount-prism",
      installsItem: true,
      target: { closeup: "foglight-console", label: "棱镜座", description: "灯罩中央有菱形镜座，下面的滑轨尚未转动。", x: 33, y: 16, width: 34, height: 45 },
      scene: "workshop",
      item: "beacon-prism",
      label: "装入雾灯棱镜",
      requires: [tool("oil-track")],
    },
  ],
  puzzles: [
    {
      ...base,
      id: "search-kit",
      scene: "gallery",
      kind: "search",
      title: "航海员的工具匣",
      inscription: "工具匣内刻着七件旧物的轮廓。找到后可以随时使用。",
      items: [
        "brush",
        "hook",
        "cloth",
        "arrow-tiles",
        "sail-tiles",
        "vane-tiles",
        "oil-can",
      ],
      success: "七件旧物已找齐，工具匣的纪念扣亮了起来。",
      hints: [
        "试着掀开能移动的遮挡物。",
        "格栅后的物件需要一件够得着的工具。",
        "观测室的卷图下面，也许有用得上的东西。",
      ],
    },
    {
      ...base,
      id: "animal-cabinet",
      scene: "gallery",
      kind: "code",
      title: "动物标本柜",
      inscription:
        "铭牌：鸟 → 蜘蛛 → 龟 → 蚂蚁。柜门上有四位密码盘。",
      easyHelp: "只数足，翅膀和触角不算。按照铭牌顺序填写。",
      requires: [tool("brush-plaque")],
      rewards: ["lens-frame"],
      length: 4,
      solution: "2846",
      animals: [
        { id: "bird", name: "鸟", legs: 2, count: 1 },
        { id: "spider", name: "蜘蛛", legs: 8, count: 1 },
        { id: "turtle", name: "龟", legs: 4, count: 1 },
        { id: "ant", name: "蚂蚁", legs: 6, count: 1 },
      ],
      success: "标本柜轻轻打开，一只光学镜架滑了出来。",
      hints: [
        "柜上的动物顺序很重要。",
        "只数足，翅膀和触角不算。",
        "把第一只鸟的脚数写在第一格，再依次观察。",
      ],
    },
    {
      ...base,
      id: "pattern-tray",
      scene: "gallery",
      kind: "arrangement",
      title: "海风纹片台",
      inscription: "三条纹带各缺两枚，台边刻着两串符号。",
      easyHelp: "朝向每次顺时针转四分之一圈，刻点按一点、两点、三点循环。分别继续两种规律。",
      requires: [tool("mount-arrow"), tool("mount-sail"), tool("mount-vane")],
      rewards: ["filter-disc"],
      slots: [
        "箭纹第3格",
        "箭纹第4格",
        "帆纹第3格",
        "帆纹第4格",
        "风标第3格",
        "风标第4格",
      ],
      pieces: [
        { id: "arrow-S3", label: "箭纹 · 南 · 三点", symbol: "↓ •••" },
        { id: "arrow-W1", label: "箭纹 · 西 · 一点", symbol: "← •" },
        { id: "sail-W1", label: "帆纹 · 西 · 一点", symbol: "◩ ← •" },
        { id: "sail-N2", label: "帆纹 · 北 · 两点", symbol: "◩ ↑ ••" },
        { id: "vane-N2", label: "风标 · 北 · 两点", symbol: "⚑ ↑ ••" },
        { id: "vane-E3", label: "风标 · 东 · 三点", symbol: "⚑ → •••" },
      ],
      solution: [
        "arrow-S3",
        "arrow-W1",
        "sail-W1",
        "sail-N2",
        "vane-N2",
        "vane-E3",
      ],
      rows: [
        { label: "箭纹", sequence: ["↑ •", "→ ••", null, null, "↑ ••"] },
        {
          label: "帆纹",
          sequence: ["◩ → ••", "◩ ↓ •••", null, null, "◩ → •••"],
        },
        { label: "风标", sequence: ["⚑ ↓ •••", "⚑ ← •", null, null, "⚑ ↓ •"] },
      ],
      success: "纹带完整地扣合，台侧升起一枚三色镜盘。",
      hints: [
        "相邻纹片不只是形状不同。",
        "分别留意朝向和刻点。",
        "朝向每次顺时针转四分之一圈，刻点按一点、两点、三点循环。分别继续两种规律。",
      ],
    },
    {
      ...base,
      id: "lens-chart",
      scene: "optics",
      kind: "filter",
      title: "变色放大镜",
      inscription:
        "锁边刻着：日 ☀ → 月 ☾ → 叶 ♧。窗内有一张纸页，镜盘可以转动。",
      easyHelp: "窗内的纸页藏着不同图层。依次转动日、月、叶镜片，观察各层。",
      requires: [tool("mount-filter")],
      rewards: ["route-plate"],
      length: 3,
      solution: "375",
      lenses: [
        {
          id: "sun",
          name: "日",
          symbol: "☀",
          color: "#d96b50",
          clue: "3",
          marks: ["贝壳", "星", "鱼"],
        },
        {
          id: "moon",
          name: "月",
          symbol: "☾",
          color: "#569ccc",
          clue: "7",
          marks: ["鱼", "浪", "锚"],
        },
        {
          id: "leaf",
          name: "叶",
          symbol: "♧",
          color: "#5b9e77",
          clue: "5",
          marks: ["锚", "帆"],
        },
      ],
      success: "观测窗的暗格打开，航路铭牌落在托盘中。",
      hints: [
        "同一张纸可能藏着不止一层。",
        "转动镜片，比较三个标记。",
        "锁旁的日、月、叶给出了观察顺序。",
      ],
    },
    {
      ...base,
      id: "gravity-lock",
      scene: "workshop",
      kind: "drop",
      title: "落块实验台",
      inscription:
        "竖直落下，碰到方块停住；记录最低小格所在行。三幅图各做一次独立实验，积木不旋转、不横移，也不消行。",
      requires: [tool("mount-route")],
      rewards: ["winding-crank"],
      boards: dropBoards,
      success: "三次落块实验吻合，抽屉弹开，露出潮汐曲柄。",
      hints: [
        "每幅图都是单独的一次下落。",
        "不能横移或转动；先找到哪一格最早碰到障碍。",
        "停住以后，读整个积木最低格的行号。",
      ],
    },
    {
      ...base,
      id: "tide-sudoku",
      scene: "optics",
      kind: "sudoku",
      title: "四方潮汐板",
      inscription:
        "每一行、每一列、每一个粗框小宫，都恰好有 1、2、3、4。深色刻字不能改动。",
      requires: [tool("wind-tide")],
      rewards: ["beacon-prism"],
      givens: [1, 0, 0, 4, 0, 4, 1, 0, 2, 0, 4, 0, 0, 3, 0, 1],
      success: "潮汐板缓缓转动，雾灯棱镜从中央升起。",
      hints: [
        "粗线圈出四个小宫。",
        "一行、一列、一个小宫都要各有1到4。",
        "找一个只缺一个数字的行、列或宫。",
      ],
    },
    {
      ...base,
      id: "foglight-console",
      scene: "workshop",
      kind: "arrangement",
      title: "归航雾灯",
      inscription:
        "六枚航路徽章，从左向右连成归港之路。",
      easyHelp: "镜片中见过的航路短图仍可回到观测窗查看。用重合的图案把短段连起来。",
      requires: [tool("mount-route"), tool("mount-prism")],
      slots: ["航路1", "航路2", "航路3", "航路4", "航路5", "航路6"],
      pieces: [
        { id: "shell", label: "贝壳", symbol: "◔" },
        { id: "star", label: "星", symbol: "★" },
        { id: "fish", label: "鱼", symbol: "⋊" },
        { id: "wave", label: "浪", symbol: "≈" },
        { id: "anchor", label: "锚", symbol: "⚓" },
        { id: "sail", label: "帆", symbol: "◭" },
      ],
      solution: ["shell", "star", "fish", "wave", "anchor", "sail"],
      success: "归航之光已点亮！温暖的光束穿过薄雾，把小船引回港湾。",
      hints: [
        "三张短图示描述的是同一段航程。",
        "找在两张图里重复出现的图案。",
        "用重合图案把短段接成长段，再摆六枚徽章。",
      ],
    },
  ],
};
