import { dropBoards } from "./dropGeometry";
import type { ChapterDefinition, Requirement } from "./types";
export const CHAPTER_KEY = "play-buddy:escape:foglight:v1";
const tool = (id: string): Requirement => ({ kind: "tool", id });
const reveal = (id: string): Requirement => ({ kind: "reveal", id });
const base = {
  easyHelp: "可以先观察实物线索，摆好后再整体确认；拿不准时可以撤销。",
  hints: [] as string[],
  requires: [] as Requirement[],
  rewards: [] as string[],
};
export const CHAPTER: ChapterDefinition = {
  id: "foglight",
  revision: 2,
  title: "归航之光",
  finish: "foglight-console",
  scenes: [
    {
      id: "gallery",
      title: "珍奇标本舱",
      description: "海鸟标本、旧纹片与航海员收藏的贝壳，守着光学镜架的秘密。",
      requires: [],
    },
    {
      id: "optics",
      title: "光学观测室",
      description: "月光穿过观测窗，三色镜片与潮汐板静静等待再次运转。",
      requires: [],
    },
    {
      id: "workshop",
      title: "雾灯工坊",
      description:
        "港湾隐在薄雾中。落块实验台旁，熄灭的雾灯还保留着温暖的铜色。",
      requires: [],
    },
  ],
  items: [
    {
      id: "brush",
      name: "软刷",
      symbol: "▰",
      description: "木柄顶端是一束细软的刷毛。",
    },
    {
      id: "hook",
      name: "长柄钩",
      symbol: "J",
      description: "细长的金属杆，末端弯成一个小钩。",
    },
    {
      id: "cloth",
      name: "镜布",
      symbol: "▱",
      description: "一块柔软、细密、不掉绒的方布。",
    },
    {
      id: "arrow-tiles",
      name: "星帆纹片",
      symbol: "↑",
      description: "两枚带箭纹与刻点的小木片，角落分别有星和帆的徽记。",
    },
    {
      id: "sail-tiles",
      name: "浪贝纹片",
      symbol: "◩",
      description: "两枚带箭纹与刻点的小木片，角落分别有浪和贝壳的徽记。",
    },
    {
      id: "vane-tiles",
      name: "锚鱼纹片",
      symbol: "⚑",
      description: "两枚带箭纹与刻点的小木片，角落分别有锚和鱼的徽记。",
    },
    {
      id: "oil-can",
      name: "小油壶",
      symbol: "♧",
      description: "铜壶里盛着润滑油，壶嘴细长。",
    },
    {
      id: "lens-frame",
      name: "放大镜架",
      symbol: "⌕",
      description: "标本柜里的光学镜架，边缘留着圆形卡槽。",
    },
    {
      id: "filter-disc",
      name: "三色镜盘",
      symbol: "◉",
      description: "日、月、叶三个标记对应三种观察镜片。",
    },
    {
      id: "route-plate",
      name: "航路铭牌",
      symbol: "▤",
      description: "长方形铜铭牌，刻着三枚向下落的方块；背面有两枚凸出的卡榫。",
    },
    {
      id: "winding-crank",
      name: "潮汐曲柄",
      symbol: "┐",
      description: "一支折角金属柄，末端是方形转轴。",
    },
    {
      id: "beacon-prism",
      name: "雾灯棱镜",
      symbol: "◇",
      description: "菱形玻璃棱镜，边缘闪着柔和的彩光。",
    },
  ],
  reveals: [
    {
      id: "pattern-engraving",
      scene: "gallery",
      label: "检查保养铭刻",
      clue: "铭刻：左上角一道斜切口，右下角两颗并排铜铆钉。",
      requires: [],
    },
    {
      id: "gallery-curtain",
      scene: "gallery",
      label: "掀开布帘",
      requires: [],
    },
    { id: "shell-fan", scene: "gallery", label: "抬起贝壳扇", requires: [] },
    { id: "rolled-chart", scene: "optics", label: "展开卷图", requires: [] },
    { id: "rope-coil", scene: "workshop", label: "移开盘绳", requires: [] },
  ],
  pickups: [
    {
      item: "brush",
      scene: "gallery",
      label: "取出布帘后的软刷",
      requires: [reveal("gallery-curtain")],
    },
    {
      item: "arrow-tiles",
      scene: "gallery",
      label: "拾起贝壳扇下的箭纹片",
      requires: [reveal("shell-fan")],
    },
    {
      item: "hook",
      scene: "optics",
      label: "取走卷图下面的长柄钩",
      requires: [reveal("rolled-chart")],
    },
    {
      item: "cloth",
      scene: "optics",
      label: "拾起望远镜旁的镜布",
      requires: [],
    },
    {
      item: "vane-tiles",
      scene: "workshop",
      label: "取出零件盘里的风标纹片",
      requires: [],
    },
    {
      item: "oil-can",
      scene: "workshop",
      label: "取走盘绳后的小油壶",
      requires: [reveal("rope-coil")],
    },
    {
      item: "sail-tiles",
      scene: "workshop",
      label: "拿起钩出的帆纹片",
      requires: [tool("hook-grate")],
    },
  ],
  tools: [
    {
      id: "brush-plaque",
      target: { closeup: "animal-cabinet", label: "积灰铭牌", description: "铭牌蒙着一层灰，刻痕看不清。", x: 20, y: 64, width: 60, height: 24 },
      scene: "gallery",
      item: "brush",
      label: "刷净标本铭牌",
      requires: [],
    },
    {
      id: "hook-grate",
      target: { closeup: "search", label: "格栅", description: "细窄的格栅后，有一叠够不到的纹片。", x: 67, y: 28, width: 27, height: 32 },
      scene: "workshop",
      item: "hook",
      label: "从格栅后钩取纹片",
      requires: [],
    },
    {
      id: "mount-arrow",
      installsItem: true,
      target: { closeup: "pattern-tray", label: "箭纹凹槽", description: "一对箭形凹槽，边缘留有卡口。", x: 10, y: 20, width: 23, height: 60 },
      scene: "gallery",
      item: "arrow-tiles",
      label: "把箭纹片放到纹片台",
      requires: [],
    },
    {
      id: "mount-sail",
      installsItem: true,
      target: { closeup: "pattern-tray", label: "帆纹凹槽", description: "一对帆形凹槽，边缘留有卡口。", x: 38, y: 20, width: 23, height: 60 },
      scene: "gallery",
      item: "sail-tiles",
      label: "把帆纹片放到纹片台",
      requires: [],
    },
    {
      id: "mount-vane",
      installsItem: true,
      target: { closeup: "pattern-tray", label: "风标凹槽", description: "一对风标形凹槽，边缘留有卡口。", x: 66, y: 20, width: 23, height: 60 },
      scene: "gallery",
      item: "vane-tiles",
      label: "把风标纹片放到纹片台",
      requires: [],
    },
    {
      id: "clean-window",
      target: { closeup: "lens-chart", label: "观测窗", description: "玻璃上的盐雾遮住了窗内的纸页。", x: 7, y: 12, width: 43, height: 75 },
      scene: "optics",
      item: "cloth",
      label: "擦净光学观测窗",
      requires: [],
    },
    {
      id: "mount-frame",
      installsItem: true,
      target: { closeup: "lens-chart", label: "镜架接口", description: "窗旁有一个圆环形接口，表面沾着盐粒。", x: 55, y: 20, width: 18, height: 60 },
      scene: "optics",
      item: "lens-frame",
      label: "装上放大镜架",
      requires: [tool("clean-window")],
    },
    {
      id: "mount-filter",
      installsItem: true,
      target: { closeup: "lens-chart", label: "镜盘卡槽", description: "侧面的圆形卡槽通向镜架，里面还没有镜盘。", x: 78, y: 20, width: 17, height: 60 },
      scene: "optics",
      item: "filter-disc",
      label: "装入三色镜盘",
      requires: [tool("mount-frame")],
    },
    {
      id: "mount-route",
      installsItem: true,
      target: { closeup: "gravity-lock", label: "铭牌嵌槽", description: "实验台下方有一块长方形空槽，槽边刻着向下落的方块。", x: 20, y: 64, width: 60, height: 24 },
      scene: "workshop",
      item: "route-plate",
      label: "将航路铭牌装上实验台",
      requires: [],
    },
    {
      id: "wind-tide",
      installsItem: true,
      target: { closeup: "tide-sudoku", label: "摇柄插孔", description: "棋盘旁的方轴孔通向停住的齿轮。", x: 75, y: 29, width: 19, height: 46 },
      scene: "optics",
      item: "winding-crank",
      label: "用曲柄启动潮汐板",
      requires: [],
    },
    {
      id: "oil-track",
      target: { closeup: "foglight-console", label: "底座轨道", description: "轨道上有干涩的锈迹，灯座卡住了。", x: 13, y: 70, width: 74, height: 19 },
      scene: "workshop",
      item: "oil-can",
      label: "润滑雾灯底座轨道",
      requires: [],
    },
    {
      id: "mount-prism",
      installsItem: true,
      target: { closeup: "foglight-console", label: "棱镜座", description: "灯罩中央有菱形镜座，下面的滑轨尚未转动。", x: 33, y: 16, width: 34, height: 45 },
      scene: "workshop",
      item: "beacon-prism",
      label: "装入雾灯棱镜",
      requires: [tool("oil-track")],
    },
  ],
  puzzles: [
    {
      ...base,
      id: "search-kit",
      scene: "gallery",
      kind: "search",
      title: "航海员的工具匣",
      inscription: "工具匣内刻着七件旧物的轮廓。找到后可以随时使用。",
      items: [
        "brush",
        "hook",
        "cloth",
        "arrow-tiles",
        "sail-tiles",
        "vane-tiles",
        "oil-can",
      ],
      success: "七件旧物已找齐，工具匣的纪念扣亮了起来。",
      hints: [
        "试着掀开能移动的遮挡物。",
        "格栅后的物件需要一件够得着的工具。",
        "观测室的卷图下面，也许有用得上的东西。",
      ],
    },
    {
      ...base,
      id: "animal-cabinet",
      scene: "gallery",
      kind: "code",
      title: "动物标本柜",
      inscription:
        "铭牌：鸟 → 蜘蛛 → 龟 → 蚂蚁。柜门上有四位密码盘。",
      easyHelp: "只数足，翅膀和触角不算。按照铭牌顺序填写。",
      requires: [tool("brush-plaque")],
      rewards: ["lens-frame"],
      length: 4,
      solution: "2846",
      animals: [
        { id: "bird", name: "鸟", legs: 2, count: 1 },
        { id: "spider", name: "蜘蛛", legs: 8, count: 1 },
        { id: "turtle", name: "龟", legs: 4, count: 1 },
        { id: "ant", name: "蚂蚁", legs: 6, count: 1 },
      ],
      success: "标本柜轻轻打开，一只光学镜架滑了出来。",
      hints: [
        "柜上的动物顺序很重要。",
        "只数足，翅膀和触角不算。",
        "把第一只鸟的脚数写在第一格，再依次观察。",
      ],
    },
    {
      ...base,
      id: "pattern-tray",
      scene: "gallery",
      kind: "arrangement",
      title: "海风纹片台",
      inscription: "方盘上留着一些固定纹片，铜框左上角有一道斜切口。",
      easyHelp: "观察固定纹片中反复出现的相同之处，再试着放入活动纹片。",
      requires: [tool("mount-arrow"), tool("mount-sail"), tool("mount-vane")],
      rewards: ["filter-disc"],
      slots: ["第一排第二格", "第一排第三格", "第二排第一格", "第二排第四格", "第三排第二格", "第四排第一格"],
      pieces: [
        { id: "star-stamp", label: "星徽纹片", symbol: "↑ •• ★", stamp: { direction: "N", dots: 2, emblem: "star" } },
        { id: "sail-stamp", label: "帆徽纹片", symbol: "← •• ◭", stamp: { direction: "W", dots: 2, emblem: "sail" } },
        { id: "wave-stamp", label: "浪徽纹片", symbol: "↓ •••• ≈", stamp: { direction: "S", dots: 4, emblem: "wave" } },
        { id: "shell-stamp", label: "贝壳徽纹片", symbol: "→ •••• ◔", stamp: { direction: "E", dots: 4, emblem: "shell" } },
        { id: "anchor-stamp", label: "锚徽纹片", symbol: "↑ • ⚓", stamp: { direction: "N", dots: 1, emblem: "anchor" } },
        { id: "fish-stamp", label: "鱼徽纹片", symbol: "↓ ••• ⋊", stamp: { direction: "S", dots: 3, emblem: "fish" } },
      ],
      solution: ["star-stamp", "sail-stamp", "wave-stamp", "shell-stamp", "anchor-stamp", "fish-stamp"],
      grid: [
        {stamp:{direction:"S",dots:2}}, {slot:0}, {slot:1}, {stamp:{direction:"E",dots:2}},
        {slot:2}, {stamp:{direction:"N",dots:4}}, {stamp:{direction:"W",dots:4}}, {slot:3},
        {stamp:{direction:"S",dots:1}}, {slot:4}, {stamp:{direction:"W",dots:1}}, {stamp:{direction:"E",dots:1}},
        {slot:5}, {stamp:{direction:"N",dots:3}}, {stamp:{direction:"W",dots:3}}, {stamp:{direction:"E",dots:3}},
      ],
      success: "纹片沉入铜框，台侧升起一枚三色镜盘。",
      hints: [
        "先比较同一排和同一列的固定纹片。",
        "方向和刻点可以分开观察。",
        "同排点数相同，同列方向相同；角落的小徽章并不决定它的位置。",
      ],
    },
    {
      ...base,
      id: "lens-chart",
      scene: "optics",
      kind: "filter",
      title: "变色放大镜",
      inscription:
        "锁边刻着：日 ☀ → 月 ☾ → 叶 ♧。窗内有一张纸页，镜盘可以转动。",
      easyHelp: "拿起放大镜，在纸上的墨痕间移动。每种镜片各有两处刻记；看到完整刻记后会抄进手记。",
      requires: [tool("mount-filter")],
      rewards: ["route-plate"],
      length: 3,
      solution: "375",
      lenses: [
        {
          id: "sun",
          name: "日",
          symbol: "☀",
          color: "#d96b50",
          clue: "3",
          marks: ["贝壳", "星", "鱼"],
        },
        {
          id: "moon",
          name: "月",
          symbol: "☾",
          color: "#569ccc",
          clue: "7",
          marks: ["鱼", "浪", "锚"],
        },
        {
          id: "leaf",
          name: "叶",
          symbol: "♧",
          color: "#5b9e77",
          clue: "5",
          marks: ["锚", "帆"],
        },
      ],
      success: "观测窗的暗格打开，航路铭牌落在托盘中。",
      hints: [
        "同一张纸可能藏着不止一层。",
        "墨痕散在港口各处。移动放大镜，再换镜片看看同一处。",
        "锁旁的日、月、叶给出了观察顺序。",
      ],
    },
    {
      ...base,
      id: "gravity-lock",
      scene: "workshop",
      kind: "drop",
      title: "落块实验台",
      inscription:
        "每槽的三块积木按 ①②③ 依次直落，不转向、不横移、不消行。全部落定后，会拼成哪个数字？",
      requires: [tool("mount-route")],
      rewards: ["winding-crank"],
      boards: dropBoards,
      success: "三个数字吻合，积木落定，抽屉弹开，露出潮汐曲柄。",
      hints: [
        "每槽单独看：最下面的 ① 先落，② 和 ③ 接着落。",
        "先在心里把 ① 放到底，再让 ② 碰到它时停下。",
        "最后放下 ③，把所有积木看成一个整体，认出数字轮廓。",
      ],
    },
    {
      ...base,
      id: "tide-sudoku",
      scene: "optics",
      kind: "sudoku",
      title: "四方潮汐板",
      inscription:
        "每一行、每一列、每一个粗框小宫，都恰好有 1、2、3、4。深色刻字不能改动。",
      requires: [tool("wind-tide")],
      rewards: ["beacon-prism"],
      givens: [1, 0, 0, 4, 0, 4, 1, 0, 2, 0, 4, 0, 0, 3, 0, 1],
      success: "潮汐板缓缓转动，雾灯棱镜从中央升起。",
      hints: [
        "粗线圈出四个小宫。",
        "一行、一列、一个小宫都要各有1到4。",
        "找一个只缺一个数字的行、列或宫。",
      ],
    },
    {
      ...base,
      id: "foglight-console",
      scene: "workshop",
      kind: "code",
      title: "归航雾灯",
      inscription: "灯座上有一排密码轮，旁边压着一枚缺角的方框印记。",
      easyHelp: "有些旧刻记在别的器物上也出现过。可以回去看看。",
      requires: [tool("mount-route"), tool("mount-prism")],
      length: 6,
      solution: "224313",
      frameSeal: true,
      success: "归航之光已点亮！温暖的光束穿过薄雾，把小船引回港湾。",
      hints: [
        "航路短图上的徽章，还在什么地方见过？",
        "有两块方盘的铜框，连缺角与铆钉的位置都一样。",
        "接好航路短图；依次找到徽章在纹片盘上的位置，再读潮汐板同一位置的数字。",
      ],
    },
  ],
};
